PSS_DIRECTORY = "PSS"
Subjects = [] #Populate this list with subject ids, Sub_1, Sub_2, etc
ARDUINO_PORT = " " #3 LETTERS PLUS NUMBER
SOA_VALUES= [-150, -100,-50,0,50,100,150]
TRIALS_PER_SOA = 20
SUBJECTS_REGISTRY = "subjects.json" 

#EEG <-SPECIFIC TO THE DEVICE
EEG_BOARD_ID = 0
EEG_SAMPLING_RATE = 250 #HZ
EEG_CHANNEL = [0,1]
"""
Fz <- index 0-> N1P
Cz <- index 1-> N2P
"""

#EEG FREQUENCY BANDS
THETA_BAND = (4.0,7.0) #tuples
ALPHA_BAND =(8.0,12.0)
GAMMA_BAND = (30.0,100.0)
DIRECTORY_NAME = "BrainData"
BLOCK3_TRIALS = 100